# Generated by Django 4.2.20 on 2026-05-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('alumni', 'Alumni'), ('intern', 'Intern'), ('faculty', 'Faculty'), ('alumni-officer', 'Alumni Officer'), ('ailpo', 'AILPO'), ('partner', 'Partner'), ('registrar', 'Registrar'), ('super-admin', 'Super Admin')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_table',
                'ordering': ['-created_at'],
            },
        ),
    ]
