# Generated by Django 4.2.20 on 2026-05-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChartMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('dean', 'Dean'), ('executive_director', 'Executive Director'), ('academic_director', 'Academic Director'), ('ailpo_coordinator', 'AILPO Coordinator'), ('other', 'Other')], default='other', max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('primary_position', models.CharField(max_length=255)),
                ('secondary_position', models.CharField(blank=True, max_length=255, null=True)),
                ('tertiary_position', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_chart_members', to='academic_records.schoolprogram')),
            ],
            options={
                'db_table': 'organization_chart_table',
                'ordering': ['display_order', 'member_type', 'full_name'],
            },
        ),
    ]
