# Generated by Django 4.2.20 on 2026-05-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0003_remove_faculty_contact_number_faculty_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('school_program_code', models.CharField(max_length=50)),
                ('school_program_full_name', models.CharField(max_length=180)),
                ('program_code', models.CharField(max_length=120)),
                ('program_full_name', models.CharField(max_length=180)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('students', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_classes', to='faculty.faculty')),
            ],
            options={
                'db_table': 'internship_classes_table',
                'ordering': ['-created_at'],
            },
        ),
    ]
