# Generated by Django 4.2.20 on 2026-05-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('super_admin', '0002_alter_superadmin_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_profile', to='accounts.account'),
        ),
    ]
