# Generated by Django 4.2.20 on 2026-05-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemaudit',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('SYSTEM', 'System'), ('CREATE_STAFF', 'Create Staff'), ('UPDATE_STAFF', 'Update Staff'), ('DELETE_STAFF', 'Delete Staff'), ('ACTIVATE_STAFF', 'Activate Staff'), ('DEACTIVATE_STAFF', 'Deactivate Staff'), ('CREATE_ACADEMIC_RECORD', 'Create Academic Record'), ('UPDATE_ACADEMIC_RECORD', 'Update Academic Record'), ('DELETE_ACADEMIC_RECORD', 'Delete Academic Record'), ('CREATE_ACADEMIC_PROGRAM', 'Create Academic Program'), ('UPDATE_ACADEMIC_PROGRAM', 'Update Academic Program'), ('DELETE_ACADEMIC_PROGRAM', 'Delete Academic Program'), ('CREATE_ORGANIZATION_CHART', 'Create Organization Chart'), ('UPDATE_ORGANIZATION_CHART', 'Update Organization Chart'), ('DELETE_ORGANIZATION_CHART', 'Delete Organization Chart'), ('UPDATE_ADMIN_PASSWORD', 'Update Admin Password')], max_length=80),
        ),
    ]
