# Generated by Django 4.2.20 on 2026-05-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academic_award_table',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='SchoolProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_program_table',
                'ordering': ['display_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='YearGraduated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'year_graduated_table',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_programs', to='academic_records.schoolprogram')),
            ],
            options={
                'db_table': 'academic_program_table',
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
