# Generated by Django 4.2.20 on 2026-05-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partner',
            table='partner_table',
        ),
    ]
