# Generated by Django 4.2.20 on 2026-05-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumni',
            table='alumni_table',
        ),
    ]
