# Generated by Django 4.2.20 on 2026-05-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransitioningAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('nu_email', models.EmailField(max_length=150, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('course_graduated', models.CharField(max_length=150)),
                ('course_graduated_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_program', models.CharField(blank=True, max_length=150, null=True)),
                ('school_program_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_period', models.CharField(max_length=100)),
                ('year_graduated', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_award', models.CharField(blank=True, max_length=150, null=True)),
                ('loyalty', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(default='alumni', max_length=30)),
                ('status', models.CharField(choices=[('transitioning', 'Transitioning'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deactivated', 'Deactivated')], default='transitioning', max_length=30)),
                ('transition_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transitioning_alumni_table',
                'ordering': ['-created_at'],
            },
        ),
    ]
